[tool.bumpversion]

current_version = "2526"
allow_dirty = true

parse = """(?x)
    (?P<release>
        (?:[0-9]{2})
        (?:[1-9ABC])
        (?:[1-9A-V])
    )
    (?:\\.(?P<patch>[1-9][0-9]*))?
"""
parts = { release = { calver_format = "{YY}{M16}{D62}" } }
serialize = ["{release}.{patch}", "{release}"]

files = [
  {filename = "docker-bake.hcl"},
  {filename = "docs/part/image-tags.md"},
  {filename = "README.md"},
  {glob = "tests/share/info/*.json"},
  {filename = "tests/test_readme_advanced/info.json"},
]
